// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMDBNXe1Bj23BZpqbEEWoHuHhR3Itn-g',
    appId: '1:822470163290:web:58a068b754492ef354d163',
    messagingSenderId: '822470163290',
    projectId: 'fir-notifications-33a06',
    authDomain: 'fir-notifications-33a06.firebaseapp.com',
    storageBucket: 'fir-notifications-33a06.appspot.com',
    measurementId: 'G-5W67GJ2PFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy3aYOa4XcVxQLzOpwP8uXfZrXQ3rL19c',
    appId: '1:822470163290:android:cf509d363bba9c8f54d163',
    messagingSenderId: '822470163290',
    projectId: 'fir-notifications-33a06',
    storageBucket: 'fir-notifications-33a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWR0mgZCHmNLlkk6wHuIIhQPjd5NdWydc',
    appId: '1:822470163290:ios:2e49f6ee8a3d830954d163',
    messagingSenderId: '822470163290',
    projectId: 'fir-notifications-33a06',
    storageBucket: 'fir-notifications-33a06.appspot.com',
    iosBundleId: 'com.example.notificationsFirebase',
  );
}
